name: scorpio
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - wget
  - biopython>=1.74
  - pip
  - python>=3.6
  - pip:
    - git+https://github.com/cov-lineages/constellations.git
